// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAweUS_41njlMhV4aoawaYcp-uxTt_MG9s',
    appId: '1:901322841013:web:756ea49989dc1ec28257fc',
    messagingSenderId: '901322841013',
    projectId: 'language-game-70882',
    authDomain: 'language-game-70882.firebaseapp.com',
    storageBucket: 'language-game-70882.firebasestorage.app',
    measurementId: 'G-45NGD1XLGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi-9YH1bQC_E0ivhNj-FCXusRusXWnw-A',
    appId: '1:901322841013:android:4255768e26bc1aa78257fc',
    messagingSenderId: '901322841013',
    projectId: 'language-game-70882',
    storageBucket: 'language-game-70882.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4TqY1Vq1q2dOjPNfaVB0hr-GTu5U6PXk',
    appId: '1:901322841013:ios:27b97db4f641b28e8257fc',
    messagingSenderId: '901322841013',
    projectId: 'language-game-70882',
    storageBucket: 'language-game-70882.firebasestorage.app',
    iosBundleId: 'com.language.game.languageGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4TqY1Vq1q2dOjPNfaVB0hr-GTu5U6PXk',
    appId: '1:901322841013:ios:27b97db4f641b28e8257fc',
    messagingSenderId: '901322841013',
    projectId: 'language-game-70882',
    storageBucket: 'language-game-70882.firebasestorage.app',
    iosBundleId: 'com.language.game.languageGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAweUS_41njlMhV4aoawaYcp-uxTt_MG9s',
    appId: '1:901322841013:web:89c0bb076ba677d88257fc',
    messagingSenderId: '901322841013',
    projectId: 'language-game-70882',
    authDomain: 'language-game-70882.firebaseapp.com',
    storageBucket: 'language-game-70882.firebasestorage.app',
    measurementId: 'G-WGQRS6L167',
  );

}